### ISSUE TITLE
No version change lines in output sometimes

### ISSUE THREAD

**Issue by dsine-de** [tjunnone/npm-check-updates#122] opened 2015-08-08 09:16 UTC
Sometimes there is no output when I run `ncu` (see Screenshot from Ubuntu 14.04 and Windows 10 PowerShell).

Other times the lines with the version updates are there, though.

![](http://i.imgur.com/L2HRDAT.png)

**Comment by metaraine** [comment] 2015-08-08 15:24
Hi! Thank you for reporting. Can you provide the dependencies in your package.json? I will need those in order to reproduce the issue.

**Comment by dsine-de** [comment] 2015-08-08 16:33
This happens i.e. with this `package.json`:

```json
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "express": "^4.13.2"
  }
}
```

**Comment by metaraine** [comment] 2015-08-08 16:50
Thanks, I will investigate!

**Comment by metaraine** [comment] 2015-08-08 23:39
Fixed in `2.1.2`. Thanks!

**Closed by metaraine** 2015-08-08 23:39 UTC
Labels: bug

**Comment by dsine-de** [comment] 2015-08-09 08:32
If I try now with the `package.json` from above, ncu outputs:
```
All dependencies match the latest package versions :)
```
It does not recognize the express version update any more.

**Comment by metaraine** [comment] 2015-08-09 13:32
This probably means that you have `4.13.3` installed. Run `npm outdated` or `npm ls --depth=0` to see what version of express is installed.

The reason we don't say you need to upgrade your package.json, is because `^4.13.2` satisfies `4.13.3`, so all you need to do is run `npm update` if you're behind. It's not recommended to constantly upgrade your package.json for backwards-compatible changes. It's the whole reason for the `^` and `~` parts of semver.

**Comment by dsine-de** [comment] 2015-08-09 14:30
Right, I forgot to clean the node_modules dir before trying again.
Thanks!
