### ISSUE TITLE
ncu doesn't update package-lock.json

### ISSUE THREAD

**Issue by falsandtru** [tjunnone/npm-check-updates#360] opened 2017-06-01 03:11 UTC
* node version: v8.0.0
* npm version: v5.0.0
* npm-check-updates version: v2.11.2

---------------------------

package.json will be updated, but package-lock.json is not. Then these two files conflict, and new versions won't actually be installed.

**Comment by falsandtru** [comment] 2017-06-01 13:13
I'm using the workaround: https://github.com/falsandtru/spica/blob/v0.0.79/gulpfile.js#L154-L156

**Comment by falsandtru** [comment] 2017-06-01 13:22
ncu makes invalid states with node 8, it is not acceptable as a standard behavior.

**Comment by karanjthakkar** [comment] 2017-06-01 14:06
@falsandtru Like @p3x-robot said, at the moment, we are a `package.json` updater. We will tell you which modules are out of date and need to be updated. Optionally, we will also update the `package.json` file for you. `package-lock.json` cannot be updated by ncu because the lockfile also contains details about the dependencies of your dependencies. This is not something ncu is aware of. An ideal flow would be for you to:

1. Use `ncu -u` to update your `package.json` to the latest package versions
2. Run `npm install` to update your `package-lock.json` file

That being said, if you can provide any more info on what `invalid states` or `conflict` it makes with node 8, I would be happy to look into that for you.

**Comment by falsandtru** [comment] 2017-06-01 14:37
Thanks for the response.

> invalid states or conflict

When we do the steps you said, you expect the update of package-lock.json by `npm install`. But package-lock.json won't actually be updated.

For exampe, when package.json and package-lock.json have a dependency which version is 1, `ncu -u` updates the dependency version of package.json to 2. After running `npm install` you expect the update of package-lock.json, but the dependency version of package-lock.json and node_modules are still 1. package.json has the different version from package-lock.json and node_modules. So they have the invalid states by the conflict.

**Comment by falsandtru** [comment] 2017-06-01 15:14
repro:

1. checkout v3.10.3 https://github.com/falsandtru/pjax-api
1. `npm i`
1. spica@0.0.77 was installed.
1. `ncu -u`
1. `spica  0.0.77  →  0.0.79` (or higher).
1. package.json was updated to spica@0.0.79.
1. `npm i`
1. package-lock.json and node_modules were not updated, still have spica@0.0.77.

**Comment by raineorshine** [comment] 2017-06-01 15:15
I agree that leaving the lock file in an invalid state is a problem.
package-lock.json didn't exist before, so it wasn't a concern. Now it must
be determined if it is within the scope of ncu or npm.

It is similar to the package.json in the sense that it is checked into
source control. It is similar to node_modules in the sense that it is
connected to the installation rather than the version specification. This
latter point makes me think that it is outside the scope of ncu. Just like
one must run `npm update` to install newer versions that were added to the
package.json, one must do something to update the package-lock.json. At the
very least ncu should inform the user of these additional required steps.

Is the package-lock.json format something we can rely on? Will it change
with new minor/patch versions of npm? This would also determine whether
it's possible to have an integrated solution.

**Comment by falsandtru** [comment] 2017-06-01 15:25
Maybe this problem should be resolved on upstream(npm). But I'm not sure about it.

**Comment by karanjthakkar** [comment] 2017-06-01 15:37
@falsandtru I was able to repro this bug locally with node 8 and npm 5.0.0 and 5.0.1. It does indeed seem like an issue with npm to me. It is already reported here: https://github.com/npm/npm/issues/16866

**Comment by falsandtru** [comment] 2017-06-01 15:40
Sounds good.

**Comment by raineorshine** [comment] 2017-06-02 19:24
> If you run npm update package-lock.json gets updated and the new dependency is installed.

If this is true, we may not need any change. This is exactly what ncu says to do.

**Comment by falsandtru** [comment] 2017-06-03 01:07
`npm update` may unexpectedly update package.json again. We should use `npm install` to update only package-lock.json.

**Comment by raineorshine** [comment] 2017-06-03 15:28
> npm update may unexpectedly update package.json again.

@falsandtru As far as I know, `npm update` will never modify the package.json. Do you have documentation of this?

**Comment by falsandtru** [comment] 2017-06-03 15:49
I ran `npm update` now. Oddly, package.json was updated with no options. Anyways, whether their options, I think there is no way to expectedly resolve the conflicts using `npm install` or `npm update` for now.

**Comment by falsandtru** [comment] 2017-06-08 05:47
FYI, now I'm using `npm i --no-shrinkwrap` after removing package-lock.json instead of updating package-lock.json to avoid this problem.

**Comment by RinkAttendant6** [comment] 2017-06-09 03:12
Yes, `npm install --no-shrinkwrap` will update the lockfile based on `package.json`. However this may have the consequences of updating more than the changed stuff in `package.json` as npm is now disregarding the lockfile, the purpose of which is to ensure deterministic installs.

**Comment by karolyi** [comment] 2017-06-09 13:29
+1, waiting for a resolution, until then I'll have to remove the `package-lock.json` to install deps from `package.json`.

**Comment by raineorshine** [comment] 2017-06-14 14:29
Thanks, I'm going to mark this as a dependency bug until we get more decisive answer on npm/npm#16866.

**Comment by kud** [comment] 2017-06-26 10:03
I've got the same problem and I think `ncu -u` should remove `package-lock.json` but maybe via another command like `--force`? 

I didn't understand the first time when I `ncu -u && npm install`ed that my modules didn't update. It's a bit confusing.

**Comment by karanjthakkar** [comment] 2017-07-06 04:03
For anyone still facing this issue, please update npm. This issue is now solved in https://github.com/npm/npm/releases/tag/v5.1.0 via https://github.com/npm/npm/pull/17508 

Since your ncu workflow should now work as it did with npm4, I'm going to close this.

**Closed by karanjthakkar** 2017-07-06 04:03 UTC
Labels: dependency-bug

**Comment by nickmccurdy** [comment] 2017-09-04 03:00
I am using `npm@5.4.0` and `npm-check-updates@2.12.1`. `ncu -u` only changes `package.json`, not `package-lock.json`. However, `package-lock.json` appears to be updated correctly if I follow the command with `npm install`. Is this intentional or is it a regression?

**Comment by raineorshine** [comment] 2017-09-04 14:33
Hi! ncu will only change package.json. The package-lock.json is outside the
scope of ncu since it is related to exact installs. ncu is just concerned
with dependency specifications.

**Comment by nickmccurdy** [comment] 2017-09-04 19:58
Thanks, I wanted to make sure. I understand if this shouldn't be default behaviour, but could a flag be added that runs `npm install` automatically? In retrospect it makes sense that ncu doesn't touch the lock, but advertising a flag could make it more obvious as well.

**Comment by raineorshine** [comment] 2017-09-04 20:19
Thanks! I will consider that change for the next version.

**Comment by raineorshine** [comment] 2018-08-26 18:35
This was fixed in npm v5.1.0. `npm install` now looks to the `package.json` as the source of truth.

https://github.com/npm/npm/pull/17508
