### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'major' of undefined

### ISSUE THREAD

**Issue by lookfirst** [tjunnone/npm-check-updates#98] opened 2015-07-12 20:21 UTC
Latest unstable:

```
Unhandled rejection TypeError: Cannot read property 'major' of undefined
    at /usr/local/lib/node_modules/npm-check-updates/lib/version-util.js:55:71
    at Array.filter (native)
    at Object.stringify (/usr/local/lib/node_modules/npm-check-updates/lib/version-util.js:54:10)
    at isUpgradeable (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:157:31)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:8201:21
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:4299:13
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:3073:15
    at baseForIn (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:2033:14)
    at pickByCallback (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:4298:7)
    at Function.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:9893:11)
    at Function.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:8152:31)
    at baseWrapperValue (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:2768:30)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:6124:14)
    at Object.upgradeDependencies (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:145:10)
    at /usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:40:39
    at tryCatcher (/usr/local/lib/node_modules/npm-check-updates/node_modules/bluebird/js/main/util.js:26:23)
```

```
  "dependencies": {
    "babel": "^5.6.14",
    "babel-runtime": "^5.6.15",
    "browser-sync": "^2.7.13",
    "connect-history-api-fallback": "^1.1.0",
    "del": "^1.2.0",
    "gulp-babel": "^5.1.0",
    "gulp-cached": "^1.1.0",
    "gulp-changed": "^1.2.1",
    "gulp-coffee": "^2.3.1",
    "gulp-concat": "^2.6.0",
    "gulp-eslint": "^0.15.0",
    "gulp-insert": "^0.4.0",
    "gulp-jshint": "^1.11.2",
    "gulp-less": "^3.0.3",
    "gulp-minify-html": "^1.0.3",
    "gulp-ng-annotate": "^1.0.0",
    "gulp-ng-html2js": "lookfirst/gulp-ng-html2js#export2",
    "gulp-notify": "^2.2.0",
    "gulp-plumber": "^1.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-replace-task": "^0.2.1",
    "gulp-sass": "^2.0.3",
    "gulp-sourcemaps": "^1.5.2",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "~3.0.6",
    "jshint-stylish": "^2.0.1",
    "karma": "^0.12.37",
    "karma-babel-preprocessor": "^5.2.1",
    "karma-chrome-launcher": "^0.2.0",
    "karma-coverage": "^0.4.2",
    "karma-jasmine": "^0.3.6",
    "karma-jasmine-html-reporter": "^0.1.8",
    "karma-jspm": "^2.0.0-beta.1",
    "karma-phantomjs-launcher": "^0.2.0",
    "karma-verbose-reporter": "0.0.3",
    "less-plugin-clean-css": "^1.5.0",
    "lodash": "^3.10.0",
    "run-sequence": "^1.1.1",
    "systemjs-route-bundler": "^1.1.1",
    "vinyl-paths": "^1.0.0"
  }
```

**Comment by metaraine** [comment] 2015-07-13 17:48
Thank you for reporting! Will investigate.

**Comment by metaraine** [comment] 2015-07-13 18:32
I couldn't reproduce from your given dependencies, but I got the error on a different package.json, so I assume it was the same bug. Pushed the fixed in 2.0.0-alpha.13. Try it out and let me know!

    npm install -g npm-check-updates@unstable

**Comment by metaraine** [comment] 2015-07-21 17:27
I'm assuming it's working now, but let me know otherwise.

**Comment by lookfirst** [comment] 2015-07-21 17:35
:+1:

**Comment by giampaolotorresi** [comment] 2017-03-29 11:59
i have the same error

**Comment by raineorshine** [comment] 2017-04-03 17:51
@giampaolotorresi Can you provide additional information including your version of node, npm, and ncu? The first step will be for us to be able to reproduce the issue.

**Comment by raineorshine** [comment] 2019-03-13 22:16
Closing due to inactivity.

**Closed by raineorshine** 2019-03-13 22:16 UTC
Labels: bug, unable-to-reproduce
