### ISSUE TITLE
TypeError: gfs.gracefulify is not a function

### ISSUE THREAD

**Issue by KrunchMuffin** [tjunnone/npm-check-updates#366] opened 2017-06-13 19:54 UTC
- [* ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [* ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 6.11 windows
* npm version: 5.0.3
* npm-check-updates 2.11.3

---------------------------
I keep getting this error even after installing fs and graceful-fs globally and locally.

(node:23976) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
var fs = gfs.gracefulify(require('fs'))
TypeError: gfs.gracefulify is not a function

**Comment by raineorshine** [comment] 2017-06-14 14:51
Similar to https://github.com/npm/npm/issues/10997

It is possible that this is caused by npm-check-updates using an internal version of npm that differs from the host machine's. This will be changed in v3, [which you can track here](https://github.com/tjunnone/npm-check-updates/milestone/2).

If that's not the issue, it is probably some kind of installation issue with `graceful-fs` that requires uninstalling and reinstalling. It would need to be reinstalled in the node_modules folder of npm-check-updates.

**Comment by KrunchMuffin** [comment] 2017-06-14 22:13
Did the 2nd option and it worked sort of. Had to also install command and
possibly something else. Don't recall. Thanks for the help.

**Comment by raineorshine** [comment] 2017-06-15 01:32
@KrunchMuffin Sure! I will close this issue as it sounds like it is resolved, unless I am misunderstanding.

**Closed by raineorshine** 2017-06-15 01:32 UTC
Labels: dependency-bug

**Comment by verlok** [comment] 2017-08-30 05:47
Same issue running jest, resolved uninstalling and installing `graceful-fs`.
Thanks guys, you're awesome.
