### ISSUE TITLE
 no such file or directory, rename dezalgo

### ISSUE THREAD

**Issue by veeramarni** [tjunnone/npm-check-updates#420] opened 2018-02-13 22:13 UTC
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [ X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 8.9.4
* npm version: 5.6.0
* npm-check-updates version: 2.14.0

---------------------------

Received followign error today only.

npm ERR! path //development/node_modules/dezalgo
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '//node_modules/npm/node_modules/dezalgo' -> '//node_modules/npm/node_modules/.dezalgo.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by sergiubologa** [comment] 2018-02-15 14:16
Same thing happens to me.

**Comment by danawoodman** [comment] 2018-02-15 20:18
Same issue here. Installing `npm-check-updates` breaks npm and removing it fixes it. Using node v9.5.0 and npm v5.6.0

**Comment by fernamp** [comment] 2018-02-19 08:39
Same here. It just works when is installed globally.

**Comment by speige** [comment] 2018-02-21 00:03
+1

**Comment by alittletf** [comment] 2018-02-24 08:22
+1

**Comment by raineorshine** [comment] 2018-02-25 10:40
This is due to an old version of `npm` being included as a dependency. This should be removed and the system `npm` should be used to make `ncu` more agnostic to the `npm` version (see multiple issues). In the mean time, I have upgraded the `npm` dependency and published to `v3.0.0-alpha1`. Let me know if this corrects the problem, and I will push it to `latest`:

```
npm install -g npm-check-updates@3.0.0-alpha1
```

**Comment by alittletf** [comment] 2018-02-26 17:46
@raineorshine  Yeah right after i posted i thought i was on npm 5.6 but i was actually on 4.6.1. What was confusing me is when I went npm -v it showed 5.6 but I noticed i was on 4.6.1 in my package.json. Anyway I upticked to the latest npm in my package.json and it solved my problem.

**Comment by raineorshine** [comment] 2018-02-28 11:20
@reft I was made aware that `npmi` also needed to be upgraded. Make sure you uninstall the package first, too. Can you try this now?

```
npm
uninstall -g npm-check-updates && npm install -g
npm-check-updates@v3-alpha
```

**Comment by franher** [comment] 2018-03-02 11:56
@raineorshine I just test `npm-check-updates@v3-alpha` it and the issue is not reproducible again.

```text
node -> v8.9.4
npm -> v5.6.0
```

Is it going to be published as a definitive release?

**Comment by raineorshine** [comment] 2018-03-04 08:09
@franher It will be published as v3, but the intention is to include the [other breaking changes](https://github.com/tjunnone/npm-check-updates/milestone/2). I am watching the repo and doing fixes where I can, but there are currently no active developers on npm-check-updates.

**Comment by trippingtarballs** [comment] 2018-03-08 10:17
> _"Same issue here. Installing npm-check-updates breaks npm and removing it fixes it. Using node v9.5.0 and npm v5.6.0"_

As a workaround I've been using;

```sh
$ npx npm-check-updates -e 1
```

[Read about `npx`](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b).

Love `npm-check-updates` 😍 Thank you for maintaining such a helpful package!

**Comment by Mathijs003** [comment] 2018-05-02 12:37
I had this issue too using npm v5.6.0, upgraded to 6.0.0 and now every installation works fine. 

run `npm i -g npm` to upgrade

**Comment by nhhockeyplayer** [comment] 2018-05-18 16:54
whats so bad about 
https://www.npmjs.com/package/npm-check

**Comment by raineorshine** [comment] 2019-02-08 12:51
Fixed in the upcoming release `v3`.

**Closed by raineorshine** 2019-02-08 12:51 UTC
Labels: bug
