### ISSUE TITLE
Warning: .settle() is deprecated

### ISSUE THREAD

**Issue by ameer157** [tjunnone/npm-check-updates#177] opened 2015-11-24 17:16 UTC
ncu throws an error:

Warning: .settle() is deprecated and will be removed in a future version. Use .reflect() instead.
    at Object.getLatestVersions (/usr/local/lib/node_modules/npm-check-updates/lib/versionmanager.js:306:20)
    at upgradePackageDefinitions (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:107:15)
    at analyzeProjectDependencies (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:162:9)
    at wrapper (/usr/local/lib/node_modules/npm-check-updates/node_modules/lodash/index.js:3533:19)
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
From previous event:
    at programRunLocal (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:380:20)
    at programRun (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:322:50)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
From previous event:
    at Object.module.exports._.merge.run (/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:403:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/bin/npm-check-updates:38:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

**Comment by glen-84** [comment] 2015-11-27 07:55
Duplicate of #174.

**Closed** 2015-11-29 19:50 UTC
