### ISSUE TITLE
ncu command not showing updates

### ISSUE THREAD

**Issue by dgroh** [tjunnone/npm-check-updates#389] opened 2017-08-31 13:24 UTC
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

I'm running `ncu` to list the updates and it says that all packages are up to date. It's not. For example, we still have references of `angular 4.0.0` and the latest is `4.3.6`.

That is our `package.json`

```json
{
  "name": "app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@progress/kendo-angular-dropdowns": "^1.0.10",
    "@progress/kendo-angular-inputs": "^1.0.6",
    "@progress/kendo-angular-intl": "^1.2.1",
    "@progress/kendo-angular-l10n": "^1.0.0",
    "@progress/kendo-angular-layout": "^1.0.3",
    "@progress/kendo-theme-default": "^2.37.1",
    "core-js": "^2.4.1",
    "ng2-localforage": "^0.1.30",
    "ng2-translate": "^5.0.0",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.3.2",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.54",
    "@types/node": "~8.0.25",
    "codelyzer": "~3.1.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "node-sass": "^4.5.3",
    "phantomjs-prebuilt": "^2.1.14",
    "protractor": "~5.1.0",
    "ts-node": "~3.3.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

```

* node version: 6.11
* npm version: 3.10.10
* npm-check-updates version: 2.12.1

---------------------------

**Comment by raineorshine** [comment] 2017-09-01 15:29
Thanks for reporting! Is it possible that the latest versions are installed in node_modules? ncu v2.x (latest) currently ignores packages that are already installed at latest. ncu v3.x (under development) will remove this functionality as it is confusing to users.

**Comment by medikoo** [comment] 2017-09-19 08:14
@raineorshine indeed that's confusing.

To me this package is purely about `package.json` maintance. Fact that lateste versions are installed should be irrelevant. I want to be sure that latest versions are referenced in `package.json` it's only use case I find for it.

**Comment by raineorshine** [comment] 2017-10-02 14:20
@medikoo Agreed!

**Comment by speige** [comment] 2017-12-28 21:29
This was fixed by raineorshine on May 27 in this commit https://github.com/tjunnone/npm-check-updates/commit/71386c98ba581abf1c6ff88c1f6a86bfa06788ad (Thanks!!!). Unfortunately, it's slated for v3. I'm guessing because it could be considered a breaking change. However, I'd consider it a critical bug fix.

Since v3 won't get to npm for a long time, I've made a fork off master with this single fix merged in. 

You can reference it in your package.json like this:
"npm-check-updates": "github:speige/npm-check-updates"

I don't plan to maintain my fork, but npm-check-updates is unusable without this fix. I'll go back to the original repo/npm as soon as this is resolved.

Thanks raine & tomas! It's an awesome package!

**Comment by speige** [comment] 2017-12-28 21:33
duplicate of #263 #261

**Comment by bs-thomas** [comment] 2018-09-01 13:46
I'm having a similar issue.  While I've read the closed issues and this one, here is my scenario.

autosize                      ^4.0.0  →   ^4.0.2

I've got this.

I understand this is a minor version upgrade.  So package.json remains as ^4.0.0.  That is completely fine if that's the way it's supposed to be.

**Trial A**
Then, doing an "npm install" after "ncu -a" I would expect it to upgrade the actual version of "autosize" to "4.0.2".

However, inspecting the actual package in "node_modules" by the following command:
    vi node_modules/autosize/package.json

gives me that the version is 4.0.0 still:
```
  ],
  "license": "MIT",
  "main": "dist/autosize.js",
  "name": "autosize",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/jackmoore/autosize.git"
  },
  "scripts": {
    "build": "node build"
  },
  "version": "4.0.0"
}
```

**Trial B**
Then, I tried to delete package-lock.json, npm install again.  Same...

**Trial C**
Then, I tried to delete node_modules/, delete package-lock.json, npm install again.  Then it worked.

=====

My understanding in terms of the usage of ncu is, to call "ncu -u", and then "npm install".  And that should upgrade all the packages I'd need to upgrade.  But that seems to not quite do the job.  So perhaps, is there something (some sort of cache?) that "ncu -u" can help flush?  I would expect all Trials A B C would upgrade the packages and yield the same end result.

Am I misunderstanding some key concepts here?  Or is there something behind this?

FYI, "autosize" is not the only package doing this.  

If anyone would be so kind to shed me some light, I'd appreciate it!

Thank you!

**Comment by speige** [comment] 2018-09-01 18:36
@raineorshine Is it worth reconsidering merging https://github.com/tjunnone/npm-check-updates/commit/71386c98ba581abf1c6ff88c1f6a86bfa06788ad to 2.14.3 as a hot-fix & publishing to npm today? It appears you're still planning to wait until v3. I don't think most people would consider this a breaking change, I think it's non-intuitive (& frustrating) behavior which makes people think this library is broken, so they stop using it.

Sorry if that sounds critical. That's not my intention. I know it's hard to find time to maintain an open-source library, especially when it's mostly for other people's benefit. We all appreciate all the hard work you've put in for us.

This will also fix #263 #261 which are duplicates & are marked closed even though the fix is not on npm.

**Comment by bs-thomas** [comment] 2018-09-02 16:12
@speige Thanks for your comment.  Looks like it's time for me to move onto npm-check.  This seems to have a more intuitive interface, tells me the breaking and non-breaking version changes, allows convenient selection of which package to update, and getting more downloads than npm-check-updates.

It looks like it's a bigger community now, and a very attractive package, I don't see any reason why I'm stalling.

Thank you very much for the advice!

**Comment by raineorshine** [comment] 2019-01-21 22:44
Closing in anticipation of branch `v3` (where this is fixed) being released soon. See #471 for roadmap.

**Closed by raineorshine** 2019-01-21 22:44 UTC
Labels: duplicate
