### ISSUE TITLE
Had to manually install npm-registry-client

### ISSUE THREAD

**Issue by i8ramin** [tjunnone/npm-check-updates#167] opened 2015-11-16 20:17 UTC
Was getting errors until I manually installed the following package:
```
npm install -g npm-registry-client
```

**Comment by metaraine** [comment] 2015-11-16 22:09
Hi Ramin, thanks for reporting. It'll be difficult to debug without knowing what errors you were getting. Are you able to reproduce? If so, please post the ncu command you were running (local or global) and the error message. Thanks!

**Comment by i8ramin** [comment] 2015-11-17 01:53
I uninstalled `npm-registry-client` and `npm-check-updates` globally ... and then re-installed `npm-check-updates` via `npm install -g npm-check-updates` and this is what I get when i run `ncu`. When i installed npm-registry-client, it all works just fine.

```
› ncu
module.js:339
    throw err;
    ^

Error: Cannot find module 'npm-registry-client'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/cache/caching-client.js:9:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/npm.js:28:26
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/npm.js:485:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
```

**Comment by metaraine** [comment] 2015-11-17 18:12
Duplicate of #168

**Closed** 2015-11-19 17:55 UTC
Labels: duplicate
