### ISSUE TITLE
Issue with module bower

### ISSUE THREAD

**Issue by mgcrea** [tjunnone/npm-check-updates#207] opened 2016-02-10 17:38 UTC
```bash
$ ncu --version
2.5.8
$ ncu -m bower

 lodash   >=2.4 <4.0  →  4undefined 
 angular      ~1.4.0  →      ~1.5.0 

Run with -u to upgrade bower.json
```

**Comment by metaraine** [comment] 2016-02-10 17:58
Thanks, looks like an issue with parsing that version range perhaps? I will investigate.

**Comment by metaraine** [comment] 2016-02-10 18:06
No, it's parsing it fine. I'm trying to test more right now but npm is causing me some issues at the moment...

**Comment by metaraine** [comment] 2016-02-10 22:33
Unfortunately I unable to reproduce on my end.

```
$ echo '{"dependencies": { "lodash": ">=2.4 <4.0" }}' | ncu -m bower

 lodash  >=2.4 <4.0  →  ^4.3 
```

(tested on `node 5.5.0/npm 3.3.12` and `node 4.2.1/npm 2.14.7`)

Someone who is able to reproduce will have to troubleshoot further.

**Comment by raineorshine** [comment] 2016-05-15 22:43
Closing in order to tidy up. I can re-open if it's still an issue and you can provide steps to reproduce.

**Closed by raineorshine** 2016-05-15 22:43 UTC
Labels: unable-to-reproduce
