### ISSUE TITLE
--newest flag doesn't update to vue-jest@4.0.0-beta.2

### ISSUE THREAD

**Issue by laggingreflex** [tjunnone/npm-check-updates#535] opened 2019-04-22 05:30 UTC
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10
* npm version: 6
* npm-check-updates version: 3.1.8

---------------------------

I have `"vue-jest": "^3.0.4"` in my project. I'm running `ncu -nu` and expect it to be updated to newest/latest version, including any beta/etc versions. 

The latest vue-jest version as I can see is [v4.0.0-beta.2](https://www.npmjs.com/package/vue-jest?activeTab=versions).

But running `ncu -nu` doesn't seem to update it to that version.

**Comment by stoically** [comment] 2019-04-22 08:14
You need to run with `--pre 1` or `--newest`, since ncu ignores prereleases by default.

**Comment by laggingreflex** [comment] 2019-04-22 08:17
@stoically I did. I've tried all of these: `-n`, `--newest`, and `--pre 1`

**Comment by laggingreflex** [comment] 2019-04-22 08:20
PS: The issue is only with vue-jest, rest of the dependencies are updating to their alpha/beta/latest versions just fine by the way.

**Comment by stoically** [comment] 2019-04-22 08:40
Oh I see, so vue-jest `3.0.4` tagged as `latest`, and ncu looks by default at the latest tag, that's why just `--pre 1` doesn't work.

`--newest` doesnt work because `3.0.4` got published after `4.0.0-beta.2`

```
4.0.0-beta.2 | "2019-02-16T16:53:50.900Z"
3.0.4 | "2019-03-04T20:16:30.979Z"
```

That would leave us with `--greatest`, but that doesn't work either because it just uses lodash's `last` on the `versions` array, which again gives us `3.0.4`. That is arguably unexpected behavior, because `4.0.0-beta.2` is greater than `3.0.4`.

**Comment by raineorshine** [comment] 2019-05-03 18:34
> That is arguably unexpected behavior, because 4.0.0-beta.2 is greater than 3.0.4.

Agreed!

**Comment by Primajin** [comment] 2019-07-10 08:38
I have a similar issue where it doesn’t seem to pick up axios in `-n` but without it does.

![Screenshot 2019-07-10 at 10 35 58](https://user-images.githubusercontent.com/1742115/60954127-c27ee600-a2fe-11e9-92de-34ab1c3a64b0.png)

**Comment by alexplumb** [comment] 2019-10-03 16:30
I frequently run into this issue with [@material-ui/lab](https://www.npmjs.com/package/@material-ui/lab). Here, the `@latest` version is `4.0.0-alpha.28` and the `@next` version is `4.0.0-alpha.12` - quite a bit older.

Is there a command I can use that will capture the latest version?

**Comment by Primajin** [comment] 2019-10-03 17:22
@alexplumb can you compare with and without `-n` (n for newest)

**Comment by alexplumb** [comment] 2019-10-03 17:26
@Primajin That picks up `@material-ui/lab@4.0.0-alpha.28` but it also picks up beta/alpha versions of all other packages. alpha.28 is the "stable" version of this particular package.

**Comment by stoically** [comment] 2019-10-03 17:59
@alexplumb `--pre 1` works in that case

**Comment by stoically** [comment] 2019-10-03 18:03
@Primajin that looks like it might be related to the caching problem which was fixed in the latest ncu version. If you encounter it again it'd be helpful if you post as new issue since that's different from OPs issue

**Comment by alexplumb** [comment] 2019-10-03 18:03
Thanks @stoically that did it

**Closed** 2019-11-28 22:41 UTC
Labels: bug

**Comment by Primajin** [comment] 2019-12-02 06:14
Is 0e368ba released yet through npm?

**Comment by stoically** [comment] 2019-12-02 06:17
No. If you open commits you can see which tags belong to it, `0e368ba` has none.

**Comment by raineorshine** [comment] 2019-12-10 17:21
Published in `v4.0.0`

**Comment by Primajin** [comment] 2019-12-12 09:58
Hmm still experiencing issues with this (`v4.0.1`) - shall I continue in here or do you prefer a fresh Issue?

![Screenshot 2019-12-12 at 10 46 41 5](https://user-images.githubusercontent.com/1742115/70702407-500b9b00-1cce-11ea-8654-bc44351440b4.png)

**Comment by raineorshine** [comment] 2019-12-12 21:38
@Primajin 

## terser-webpack-plugin

In your initial execution of `ncu -n -i -u`, I can't explain why `terser-webpack-plugin` does not appear at all. It appears fine for me:

```sh
raine[535]$ cat package.json
{
  "dependencies": {
    "terser-webpack-plugin": "^2.2.2"
  }
}
raine[535]$ ncu -n -i -u
Upgrading /Users/raine/projects/ncu-troubleshooting/535/package.json
[====================] 3/3 100%
? Do you want to upgrade: terser-webpack-plugin ^2.2.2 → ^2.3.0? › (Y/n)

 terser-webpack-plugin  ^2.2.2  →  ^2.3.0

Run npm install to install new versions.
```

## axios

`0.18.1` was published *after* `0.19.0`, thus ncu correctly returns `0.18.1` as the newest possible version:

```js
raine[535]$ npm view axios time

{
  ...
  '0.18.0': '2018-02-19T23:28:54.151Z',
  '0.19.0-beta.1': '2018-08-09T18:44:25.247Z',
  '0.19.0': '2019-05-30T16:13:16.930Z',
  '0.18.1': '2019-06-01T00:46:36.277Z'
}
```

## @types/node

`10.17.9` was published *after* `12.12.17`, thus ncu correctly returns `10.17.9` as the newest possible version:

```js
raine[535]$ npm view @types/node time

{
  ...
  '12.12.16': '2019-12-09T20:46:09.689Z',
  '10.17.8': '2019-12-09T20:46:55.283Z',
  '12.12.17': '2019-12-10T19:21:19.425Z',
  '10.17.9': '2019-12-10T19:22:05.828Z'
}
```

You can use `--greatest` or `-t` to get the *highest* version, regardless of publish time.

**Comment by stoically** [comment] 2019-12-13 02:50
@Primajin If you could share the package.json being used, it might be possible to reproduce the `terser-webpack-plugin` problem, maybe its because of a combination of packages or something.

**Comment by Primajin** [comment] 2019-12-13 05:36
Thank you very much for all the effort! I'll see if I go with greatest then instead of newest.

**Comment by Primajin** [comment] 2019-12-13 10:48
![Screenshot 2019-12-13 at 11 46 47](https://user-images.githubusercontent.com/1742115/70794648-654ffa80-1d9e-11ea-824b-3ec75e116b44.png)

`-t` (greatest) solves it for me - thanks a lot everyone!
