### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by AdamHess** [tjunnone/npm-check-updates#143] opened 2015-09-28 16:59 UTC
tried running NCU while using v4.1.1 of Node and all i get is a carrage return and a blank line for a solid 20 minutes. If i run it on another operating system it runs in under 3-4 minutes.

**Comment by metaraine** [comment] 2015-09-28 19:36
Hi Adam, thanks for reporting. This is a difficult bug to troubleshoot, as I am not running Windows. You are not the only one who has had it stall out, so I wonder what it causing it. 

Is it working on Windows for anyone else?

One thing to try is deleting the node_modules folder completely then trying again. That seemed to help at least one person who was running into this problem. 

If that doesn't work, we may be able to track down the problem better when we refactor the code to perform incremental installs, instead of all at once. Then at least there would be a progress bar.

**Comment by AdamHess** [comment] 2015-09-28 21:32
OMG yes, i need a status bar it would make me so happy...or at least a "verbose" mode.

**Comment by frantzyy** [comment] 2015-10-02 11:33
Works for me takes a really really really long time. Agree on some status bar.

Some baselines...
~5 mins when checking express
~1 min when checking gulp-replace
~? haven't waited long to see results when checking karma

I found it helpful to use the --dev option since I'm only really looking to see if I need tooling updates. 

I ran all the test under npm-check-updates and they all passed (93 passing in 48s)

My setup....
Windows 7 64
node 4.0.0
npm 2.14.2

**Comment by metaraine** [comment] 2015-10-03 14:42
Thanks Chris! Helpful to know it is working on Windows, just very slow. I will make the progress bar a higher priority.

**Comment by johanhelsing** [comment] 2015-10-19 11:16
I'm trying to use it on windows. I have waited for 5 minutes with just a blank line.

Would be great to have a progress bar, and or verbose mode to at least see that something is happending.

**Comment by metaraine** [comment] 2015-10-19 19:48
Thanks Johan. That's not a great user experience. I hope that the [async output](https://github.com/tjunnone/npm-check-updates/tree/progress-bar) which will show the progress of each package helps this situation.

**Comment by elektronik2k5** [comment] 2015-11-03 11:40
+1 for progress or increased verbosity

**Comment by raineorshine** [comment] 2016-06-08 16:27
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.

**Closed by raineorshine** 2016-06-08 16:27 UTC
Labels: enhancement

**Comment by felipenmoura** [comment] 2017-12-12 17:17
Hi.
I'm using it programatically. I have a note service that starts and uses it in the background to asynchronously look for updates.
The problem is that even when it has finished, the status bar stays in the terminal!
I'm using `silent: true` in the options and also `loglevel`

```js
ncu.run({
                packageFile: this.paths.project + '/package.json',
                silent: true,
                jsonUpgraded: true,
                upgrade: false,
                loglevel: 'silent',
                version: true,
                upgradeAll: true
            }).then(async outdated => {
  ...
})
```

Is there a way I can turn the progress bar off??

After it has finished, it looks like this:

<img width="355" alt="screen shot 2017-12-12 at 15 16 38" src="https://user-images.githubusercontent.com/347387/33898431-882e8862-df4f-11e7-9dd7-5c467f601c47.png">
