### ISSUE TITLE
'ncu' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by lorenzosjb** [tjunnone/npm-check-updates#266] opened 2016-09-08 19:32 UTC
Please include the ncu path to the install process because after installing in Windows 7 without any errors and executing ncu command. This is my output. Thanks for the help.

C:\Users\jimenelo>npm install -g npm-check-updates
C:\Users\jimenelo\AppData\Roaming\npm\ncu -> C:\Users\jimenelo\AppData\Roaming\npm\node_modules\npm-check-updates\bin\ncu
C:\Users\jimenelo\AppData\Roaming\npm\npm-check-updates -> C:\Users\jimenelo\AppData\Roaming\npm\node_modules\npm-check-updates\bin\npm-check-updates
C:\Users\jimenelo\AppData\Roaming\npm
`-- npm-check-updates@2.8.0

C:\Users\jimenelo>npm -g ls --depth=0
C:\Users\jimenelo\AppData\Roaming\npm
+-- create-react-app@0.3.0
+-- express-generator@4.13.4
+-- npm-check-updates@2.8.0
`-- swagger@0.7.5

C:\Users\jimenelo>ncu
'ncu' is not recognized as an internal or external command,
operable program or batch file.

**Comment by lorenzosjb** [comment] 2016-09-08 20:41
Found out what was the problem. A mix of paths

**Comment by raineorshine** [comment] 2016-09-09 15:28
Hi, thanks for reporting! A couple questions.

Is `npm-check-updates` not found as well?
Does the same problem occur for any global npm module, or just `ncu`?

**Comment by arturparkhisenko** [comment] 2016-09-26 06:55
@raineorshine got the same error today, node v6.6.0, npm 3.10.3. 
Either `ncu` or `npm-check-updates` is found.
`npm list -g --depth=0` shows that npm-check-updates@2.8.0 is installed, and i already tried to reinstall it.

**Comment by raineorshine** [comment] 2016-10-02 21:03
Okay, closing :)

**Closed by raineorshine** 2016-10-02 21:03 UTC

**Comment by PixelWeaver** [comment] 2019-07-22 10:08
> 
> 
> @raineorshine got the same error today, win10pro, **node v6.6.0**, npm 3.10.3.
> Either `ncu` or `npm-check-updates` aren't found (global ofc).
> `npm list -g --depth=0` shows that npm-check-updates@2.8.0 is installed, and i already tried to reinstall it.
> 
> ~Wow.. maybe it's not fault of npm-check-updates, i found that bower and etc not working too).. looking why.~
> **Repaired NodeJS and everything works fine. Thanks)**

What do you mean by repairing NodeJS ? Did you uininstall/reinstall ?

**Comment by arturparkhisenko** [comment] 2019-07-22 14:15
@PixelWeaver I've found I had multiple nodejs versions and I suppose it was required to switch from one to another after a `brew` update. And maybe one of the second issues I have found was that in my shell config file (ex.: `.zshrc`) I did the wrong `PATH` export (now every time I Install Node it asks me to do a new export, where I also should remove the previous one.

**Comment by abhi007tyagi** [comment] 2020-02-06 18:07
Either ncu or npm-check-updates aren't found after installing!

**Comment by Flexxkii** [comment] 2020-02-14 20:38
> Either ncu or npm-check-updates aren't found after installing!
> 
> PS E:\Abhinav_Workspace\NodeProject> ncu
> ncu : The term 'ncu' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
> spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> 
> * ncu
> * ```
>     + CategoryInfo          : ObjectNotFound: (ncu:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```
> 
> PS E:\Abhinav_Workspace\NodeProject> npm-check-updates
> npm-check-updates : The term 'npm-check-updates' is not recognized as the name of a cmdlet, function, script file, or
> operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
> again.
> At line:1 char:1
> 
> * npm-check-updates
> * ```
>     + CategoryInfo          : ObjectNotFound: (npm-check-updates:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

You need to install npm-check-updates globally
So
npm install -g npm-check-updates

now do 
ncu

**Comment by pekumar7** [comment] 2020-05-04 10:03
Same thing happening for me on windows .. @Flexxkii  -installed successfully ( install npm-check-updates globally) but ncu not working

**Comment by hermit-Z** [comment] 2020-12-27 19:31
hello everyone, I have corrected this problem with the following instructions:
sudo npm install -g npm-check-updates

**Comment by vchabal** [comment] 2021-01-19 18:47
The problem is that `node_modules/pm2-windows-service/package.json` has incompatible dependency version of `inquirer`. Command `ncu inquirer -u` updated `inquirer` to version `^7.3.3` which fixes the problem.

To help others with understanding of this issue, i'm including part of my configuration. See `init` script.
As well I recommend you to read [stackoverflow anwer](https://stackoverflow.com/questions/42758985/windows-auto-start-pm2-and-node-apps#answer-42770772) to configure the pm2 service.
```
  "devDependencies": {
    "npm-check-updates": "^10.2.5",
    "pm2-windows-service": "^0.2.1"
  },
  "scripts": {
    "init": "npm install && npm run ncu-pm2 && npm run create",
    "create": "pm2-service-install -n pm2-service",
    "ncu-pm2": "cd node_modules/pm2-windows-service && ncu inquirer -u && cd ../.. && npm install"
  },
```

**Comment by hosseinGanjyar** [comment] 2021-04-17 08:22
I had this problem and solved by this solutiob:

Run npm config get prefix and check the correct npm path first and append the output to the PATH using command or adding manually.

`npm config get prefix    => 
C:\mydev\tools\npm\npm`

`set PATH=%PATH%;C:\mydev\tools\npm\npm`
