### ISSUE TITLE
ncu does not filter out non release versions when setting semverLevel

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [tjunnone/npm-check-updates#437] opened 2018-05-11 19:44 UTC
- [X ] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X ] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version:  9.6.1
* npm version: 6.0.0
* npm-check-updates version: 2.14.2

---------------------------

This occurs when you set the semver level to either major or minor. For example, when I ran ncu on my program it outputted

` typescript                          2.8.1  →  2.9.0-insiders.20180510`

After looking through the trunk code, this is because the findGreatestByLevel function do no filtering on versions. This can be problematic. If you're updating major or minor versions, you probably want a stable build. 

Fortunately, I can think of two simple solutions:

1.  Simple Regex: Because npm packages use semantic versioning, we can simply filter out anything that doesn't match a regex
2.  Leveraging SemverUtils. We already use semverutils in findGreatestByLevel. If we assume that anything that has a .release (in this case 'insiders.20180510') is not a stable build, then we can filter based off of that. 

Let me know if either solution works for you.

**Comment by raineorshine** [comment] 2018-05-14 16:35
Hey! Thanks for reporting. I'd like to clarify to make sure I understand.

You are just talking about using `--semverLevel`, yes? Can you say a little more what your use case is for that flag in particular? It was a specific feature added by another contributor that shouldn't be necessary in most cases.

**Comment by JustAnotherSoftwareDeveloper** [comment] 2018-05-14 16:57
You are correct, I am talking about the --semverLevel option.

Basically, I work at a company that has an automated build and source code manger. One thing we do is, after release, update minor versions of dependencies to their latest build. For java (with Maven), we have the maven-versions-plugin that accomplishes this nicely. However, we don't have anything in place for NPM. It's been sort of a pet peeve of mine. 

The problem with the current implementation is that it will update minor versions to unstable builds. For example, consider the following scenario:

Project A depends on lib B v 1.1.1. 
There are the following versions of the lib available
2.0
1.2
1.2.1-prerelease

Using the --semverLevel minor will update to the last version. Not only is this problematic as the last version isn't stable, I don't think it's in the spirit of specifying the semver level. I used the typescript example as one that affects anyone pulling from the standard NPM repo. 

I understand the I could use the ~ and ^ operators, but we prefer to NOT use version ranges for a number of reasons. 

We want to use the semver level to minimize breakage. An example that, again, lives on the NPM repo is rxjs. RXJS 5.5.10 is fine for us, but 6.0.0 introduces breaking changes. While obviously technically ANY version can do this, minor versions tend to be a lot safer in this regard. 

If backwards compatibility is needed, a "minor/major-stable" option could be added with the predicate changes described above. 

Does that answer your question? If not, please let me know. I'd be happy to fill in any blanks.

**Comment by karanjthakkar** [comment] 2018-05-14 20:50
Hello! I noticed that this seems to be related to one of the features that I was working on which was merged(#311) but then unfortunately reverted because it broke semver(#322). I think that flag makes much more sense than adding new semver levels like minorStable etc since you can combine it with semver level. It's been on the backburner for v3 but if someone were to update the implementation to --no-pre instead of --pre, then we can get it in 2.x if you're fine with it 🙂

**Comment by raineorshine** [comment] 2018-05-15 19:33
@JustAnotherSoftwareDeveloper That is a good summary of the two positions. I guess I would say I am 1 with exceptions :). And exceptions can be more or less dangerous.

@karanjthakkar Ah yes, it's all coming back now :). Very similar discussion in #308. I had forgotten about that.

Given this new information I think we should just push for a v3 release (anybody? please? ☺️) with the `--pre`` tag opt-in. Then the default behavior will fix this issue. Thoughts?

**Comment by karanjthakkar** [comment] 2018-05-15 19:39
@raineorshine I think v3 has been a long time coming. I have some extra time to give for this. Let's do it. How can I help? Been out of touch with things for a while. We can continue this conversation on gitter too if its tertiary to this issue.

**Comment by raineorshine** [comment] 2018-05-15 19:46
@karanjthakkar Would *really* appreciate it. It would be a great step. Let's chat on gitter on in a general issue for [v3](https://github.com/tjunnone/npm-check-updates/milestone/2).

**Comment by JustAnotherSoftwareDeveloper** [comment] 2018-05-17 18:09
I'm cool with the proposed solution

**Comment by raineorshine** [comment] 2019-01-28 20:36
Duplicate of #368. Implemented in soon-to-be-released v3.

**Closed by raineorshine** 2019-01-28 20:36 UTC
