### ISSUE TITLE
ncu broken with Node 8.0.0-rc1

### ISSUE THREAD

**Issue by juergenzimmermann** [tjunnone/npm-check-updates#355] opened 2017-05-27 15:15 UTC
After replacing Node 7.10 with 8.0.0-rc.1 I get the following stacktrace when invoking `ncu`:

```
C:\workspace\software-engineering\angular-mean>ncu
C:\Zimmermann\npm-config\node_modules\npm-check-updates\node_modules\require-dir\index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (C:\Zimmermann\npm-config\node_modules\npm-check-updates\node_modules\require-dir\index.js:97:37)
    at Object.<anonymous> (C:\Zimmermann\npm-config\node_modules\npm-check-updates\lib\versionmanager.js:8:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Zimmermann\npm-config\node_modules\npm-check-updates\lib\npm-check-updates.js:14:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

**Comment by raineorshine** [comment] 2017-05-27 16:49
This appears to be an issue with the `require-dir` module. I have [created an issue](https://github.com/aseemk/requireDir/issues/45) and will followup accordingly. Thanks!

**Comment by betimer** [comment] 2017-05-31 01:53
Also appears on my laptop. And now node 8 is not RC, it is officially released.
Expect to see the fix. Thank you.

**Comment by pakastin** [comment] 2017-05-31 08:16
yup, still broken in Node.js 8 stable as well..

**Comment by bonesoul** [comment] 2017-05-31 08:56
exactly

**Comment by moeseth** [comment] 2017-05-31 09:33
Same here as well!

**Comment by kerrisharp** [comment] 2017-05-31 09:40
Getting this issue today after a Node update

**Comment by vecernik** [comment] 2017-05-31 13:01
same on node8@osx

**Comment by jharris4** [comment] 2017-05-31 13:49
I copied the fix from the PR to require-dir https://github.com/aseemk/requireDir/pull/46/files into my global install of npm-check-updates, and it fixed the issue.

Guess we'll have to wait until the PR is merged and there's a newer version of require-dir.

**Comment by outaTiME** [comment] 2017-05-31 13:56
same =(

**Comment by Sethios** [comment] 2017-05-31 13:57
+1

**Comment by JoshLWScott** [comment] 2017-05-31 13:58
Take a look at @jharris4 's pull file, simply replace the line and things will be working as intended until it's merged.

**Comment by outaTiME** [comment] 2017-05-31 14:12
Thanks, im using the require-dir PR patch now

**Comment by raineorshine** [comment] 2017-05-31 16:18
requre-dir `0.3.2` was published with the fix. Should be fixed now without any special patches, just run `npm update -g npm-check-updates`. (Or maybe you have to uninstall and re-install? Not sure since ncu's version is not changing, just the underlying require-dir dependency.)

**Closed by raineorshine** 2017-05-31 16:18 UTC
Labels: dependency-bug

**Comment by jharris4** [comment] 2017-05-31 16:21
I might have recommended bumping the semver of require-dir in package.json to `^0.3.2` and tagging a new release, but heh.

**Comment by raineorshine** [comment] 2017-05-31 16:27
@jharris4 `^0.3.1` includes `0.3.2` (semver).

**Comment by jharris4** [comment] 2017-05-31 16:33
@raineorshine right, but my point was that `^0.3.2` is now required for ncu to work properly with Node 8, and `^0.3.1` is not sufficient (becomes important if you're using something like yarn lock files etc)

**Comment by mathiasbynens** [comment] 2017-05-31 16:43
> Or maybe you have to uninstall and re-install?

Confirmed: I needed to uninstall and then re-install.

```sh
npm uninstall npm-check-updates -g && npm install npm-check-updates -g
```

**Comment by raineorshine** [comment] 2017-05-31 17:16
@jharris4 

> right, but my point was that ^0.3.2 is now required for ncu to work properly with Node 8, and ^0.3.1 is not sufficient (becomes important if you're using something like yarn lock files etc)

Ah, you are right!

**Comment by jharris4** [comment] 2017-05-31 18:10
@mathiasbynens Just FYI, with npm 5.0.0 (which I just upgraded to) there are some problems uninstalling global packages. I had to re-install without uninstalling, but it worked.

Here's a link to the issue on npm: https://github.com/npm/npm/issues/16738

**Comment by webjay** [comment] 2017-05-31 19:10
`npm uninstall npm-check-updates -g && npm install npm-check-updates -g` works.

**Comment by jharris4** [comment] 2017-05-31 19:26
@webjay Are you using npm 5.0.0 with npm-check-updates previously installed with npm 4.x?

**Comment by webjay** [comment] 2017-05-31 19:29
@jharris4 I'm using npm 4.2.0 and node v8 on a Mac.

**Comment by jharris4** [comment] 2017-05-31 20:07
@webjay I guessed as much. I'm using homebrew to install node on a Mac too :-)

**Comment by hezhongfeng** [comment] 2017-06-01 00:15
@webjay Thank you! It works.

**Comment by synapticism** [comment] 2017-06-03 21:18
I'm on OS X with Node installed by brew and npm installed separately. The uninstall also didn't work but `npm install npm-check-updates -g` alone seems to have fixed things up.

**Comment by heldrida** [comment] 2017-06-22 09:27
El Capitan 10.11.6 / homebrew upgrade node v8.1.2 / npm v5.0.3

the attempt for `npm uninstall npm-check-updates -g && npm install npm-check-updates -g` fails with:

`Unhandled rejection Error: Argument #2: Expected string but got nullf8dfac7a8f7b
    at addDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /usr/local/lib/node_modules/npm/lib/install/deps.js:463:5
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/usr/local/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /usr/local/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/usr/local/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Helder/.npm/_logs/2017-06-22T09_24_53_902Z-debug.log`

**Comment by Nirbhay94** [comment] 2017-07-15 12:38
sudo apt-get remove nodejs

sudo apt-get remove npm

Then go to /etc/apt/sources.list.d and remove any node list if you have. Then do a

sudo apt-get update

Check for any .npm or .node folder in your home folder and delete those.

If you type

which node

you can see the location of the node. Try which nodejs and which npm too

Now install node.js

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by Ankiewicz** [comment] 2017-11-06 19:29
I was able to resolve this quick because I have NVM installed. I just switched to a different version of Node.

I was using `node -v = v8.7.0`
switched to `v6.2.2`
