### ISSUE TITLE
Exclude Issue - Bug

### ISSUE THREAD

**Issue by syedsimanta03** [tjunnone/npm-check-updates#533] opened 2019-04-19 11:47 UTC
bootstrap                   ^3.3.7  →   ^4.3.1
 vue                         ^2.0.1  →  ^2.6.10
 babel-core                  ^6.0.0  →  ^6.26.3
 babel-loader                ^6.0.0  →   ^8.0.5
 babel-preset-es2015         ^6.0.0  →  ^6.24.1
 cross-env                   ^3.0.0  →   ^5.2.0
 css-loader                 ^0.25.0  →   ^2.1.1
 file-loader                 ^0.9.0  →   ^3.0.1
 vue-loader                  ^9.7.0  →  ^15.7.0
 webpack              2.1.0-beta.25  →   4.30.0
 webpack-dev-server    2.1.0-beta.0  →    3.3.1

==============================

I used ncu -u -x 'bootstrap'  . But unable to exclude bootstrap. Because I want to use B3 not B4 version. It also upgraded the bootstrap to version 4 
* node version: latest
* npm version: latest
* npm-check-updates version: latest

---------------------------

![Snap 2019-04-19 at 17 46 54](https://user-images.githubusercontent.com/24764973/56422806-28913980-62cb-11e9-924e-6bbae5a24fa0.png)

**Comment by raineorshine** [comment] 2019-04-19 16:56
I am unable to reproduce. `ncu -u -x 'bootstrap'` works correctly for me.

**Comment by syedsimanta03** [comment] 2019-04-19 17:00
please check now

**Comment by syedsimanta03** [comment] 2019-04-19 17:01
{
  "name": "myvue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^2.6.5",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.6.0",
    "@vue/cli-plugin-eslint": "^3.6.0",
    "@vue/cli-service": "^3.6.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-template-compiler": "^2.5.21"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**Comment by stoically** [comment] 2019-04-19 17:14
There's no bootstrap in that example?

**Comment by syedsimanta03** [comment] 2019-04-19 17:15
please add b3

**Comment by stoically** [comment] 2019-04-19 17:19
Works as expected for me.

**Comment by syedsimanta03** [comment] 2019-04-19 17:21
I appreciate your help. But Can u exactly write commands u used to upgrade all packages except bootstrap 3?

**Comment by stoically** [comment] 2019-04-19 17:26
I've also tried `ncu -u -x 'bootstrap'`.

**Comment by raineorshine** [comment] 2019-06-13 14:38
Closing as two people have been unable to reproduce. @syedsimanta03 Let us know if you're still having difficulties!

**Closed by raineorshine** 2019-06-13 14:38 UTC
Labels: unable-to-reproduce
