### ISSUE TITLE
ncu -m bower command errors out

### ISSUE THREAD

**Issue by MCKRUZ** [tjunnone/npm-check-updates#172] opened 2015-11-19 14:41 UTC
when running with the latest version using the command line
ncu -m bower I get this error

Unhandled rejection SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/mattkruczek/.npm-packages/lib/node_modules/npm-check-updates/node_modules/bower/node_modules/bower-json/lib/json.js:41:29
    at /Users/mattkruczek/.npm-packages/lib/node_modules/npm-check-updates/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by metaraine** [comment] 2015-11-19 16:25
Can you post your bower.json?

**Comment by MCKRUZ** [comment] 2015-11-19 16:26
{
  "name": "Momentum.EnterpriseTemplate",
  "version": "1.0.0",
  "authors": [
    "MCKRUZ"
  ],
  "description": "",
  "main": "[]",
  "moduleType": [
    "es6"
  ],
  "keywords": [
    "Momentum.EnterpriseTemplate"
  ],
  "license": "MIT",
  "homepage": "http://www.tallan.com",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "angular": "~1.4.7",
    "angular-animate": "~1.4.7",
    "angular-route": "~1.4.7",
    "angular-sanitize": "~1.4.7",
    "angular-ui-bootstrap-bower": "~0.14.3",
    "angular-ui-router": "~0.2.15",
    "angular-vs-repeat": "~1.0.0-rc9",
    "angularjs-breakpoint": "*",
    "blueimp-gallery": "~2.16.0",
    "chartjs": "~1.0.2",
    "jquery": "~2.1.4",
    "jqueryui": "~1.11.4",
    "jquery-validate": "~1.14.0",
    "metisMenu": "~2.2.0",
    "ng-idle": "~1.1.1",
    "ocLazyLoad": "~1.0.8",
    "slimScroll": "~1.3.6",
    "ui-scroll": "~1.3.0",
    "validate": "~0.9.0",
    "moment": "~2.10.6",
    "raphael": "~2.1.4",
    "yao.g.raphael": "*",
    "ngprogress": "~1.1.2",
    "d3": "~3.5.8",
    "esprima": "~2.0.0",
    "morrisjs": "~0.5.1",
    "jquery.ui.touch-punch.dk": "~0.3.3",
    "dropzone": "~4.2.0",
    "sweetalert": "~1.1.3",
    "jasmine": "~2.3.4",
    "angular-mocks": "~1.4.7",
    "pace": "~1.0.2",
    "excanvas": "*",
    "fontawesome": "~4.4.0",
    "bootstrap": "~3.3.5",
    "angular-translate": "~2.8.1",
    "angular-translate-loader-url": "~2.8.1",
    "breezejs-angular": "~0.8.7",
    "breeze-client-labs": "~1.5.8",
    "breeze-client": "~1.5.4",
    "angular-toastr": "~1.5.0",
    "stacktrace-js": "~1.0.1",
    "q": "~2.0.2",
    "angular-signalr-hub": "~1.5.0",
    "angulartics": "~0.20.1",
    "ua-parser-js": "~0.7.9",
    "angular-dynamic-locale": "~0.1.28",
    "lodash": "~3.10.1",
    "angulartics-google-analytics": "~0.1.1",
    "angulartics-mixpanel": "~0.1.1",
    "angulartics-segment": "~0.1.2",
    "angulartics-facebook-pixel": "~0.1.0",
    "angulartics-flurry": "~0.1.1",
    "angulartics-for-mixpanel": "~1.0.1",
    "angulartics-kissmetrics": "~0.1.1",
    "angulartics-adobe-analytics": "~0.1.1",
    "angulartics-calq": "~0.1.1",
    "angulartics-chartbeat": "~0.1.1",
    "angulartics-coremetrics": "~0.0.1",
    "angulartics-localytics": "~0.1.1",
    "angular-extend-promises": "~1.0.0-rc.3",
    "angular-translate-loader-static-files": "~2.8.1",
    "angular-translate-handler-log": "~2.8.1",
    "error-stack-parser": "~1.2.3",
    "stackframe": "~0.3.1",
    "stack-generator": "~1.0.7",
    "stacktrace-gps": "~2.3.1"
  }
}

**Comment by metaraine** [comment] 2015-11-19 16:37
I'm afraid it worked for me!

"Unexpected end of input" implies that the bower.json cannot be read correctly, but I'm not sure how to debug further without being able to reproduce.

```
$ ncu -m bower

 angular-toastr      ~1.5.0  →  ~1.6.0 
 error-stack-parser  ~1.2.3  →  ~1.3.0 

Run with -u to upgrade bower.json

The following dependencies are satisfied by their declared version range, but the installed versions are behind. You can install the latest versions without modifying your package file by using bower update. If you want to update the dependencies in your package file anyway, use --upgradeAll.

 slimScroll                     ~1.3.6  →   ~1.3.7 
 d3                             ~3.5.8  →   ~3.5.9 
 angulartics                   ~0.20.1  →  ~0.20.2 
 angulartics-google-analytics   ~0.1.1  →   ~0.1.2 
 stacktrace-gps                 ~2.3.1  →   ~2.3.2 
```

**Comment by MCKRUZ** [comment] 2015-11-19 16:39
This is the file that is having the error

var fs = require('graceful-fs');
var path = require('path');
var deepExtend = require('deep-extend');
var isComponent = require('./util/isComponent');
var createError = require('./util/createError');

var possibleJsons = ['bower.json', 'component.json', '.bower.json'];

function read(file, options, callback) {
    if (typeof options === 'function') {
        callback = options;
        options = {};
    }

    // Check if file is a directory
    fs.stat(file, function (err, stat) {
        if (err) {
            return callback(err);
        }

        // It's a directory, so we find the json inside it
        if (stat.isDirectory()) {
            return find(file, function (err, file) {
                if (err) {
                    return callback(err);
                }

                read(file, options, callback);
            });
        }

        // Otherwise read it
        fs.readFile(file, function (err, contents) {
            var json;

            if (err) {
                return callback(err);
            }

            try {
                json = JSON.parse(contents.toString());
            } catch (err) {
                err.file = path.resolve(file);
                err.code = 'EMALFORMED';
                return callback(err);
            }

            // Parse it
            try {
                json = parse(json, options);
            } catch (err) {
                err.file = path.resolve(file);
                return callback(err);
            }

            callback(null, json, file);
        });
    });
}

function parse(json, options) {
    options = deepExtend({
        normalize: false,
        validate: true,
        clone: false
    }, options || {});

    // Clone
    if (options.clone) {
        json = deepExtend({}, json);
    }

    // Validate
    if (options.validate) {
        validate(json);
    }

    // Normalize
    if (options.normalize) {
        normalize(json);
    }

    return json;
}

function validate(json) {
    if (!json.name) {
        throw createError('No name property set', 'EINVALID');
    }

    // TODO

    return json;
}

function normalize(json) {
    if (typeof json.main === 'string') {
        json.main = json.main.split(',');
    }

    // TODO

    return json;
}

function find(folder, files, callback) {
    var err;
    var file;

    if (typeof files === 'function') {
        callback = files;
        files = possibleJsons;
    }

    if (!files.length) {
        err = createError('None of ' + possibleJsons.join(', ') + ' were found in ' + folder, 'ENOENT');
        return callback(err);
    }

    file = path.resolve(path.join(folder, files[0]));
    fs.exists(file, function (exists) {
        if (!exists) {
            return find(folder, files.slice(1), callback);
        }

        if (files[0] !== 'component.json') {
            return callback(null, file);
        }

        // If the file is component.json, check it it's a component(1) file
        // If it is, we ignore it and keep searching
        isComponent(file, function (is) {
            if (is) {
                return find(folder, files.slice(1), callback);
            }

            callback(null, file);
        });
    });
}

module.exports = read;
module.exports.read = read;
module.exports.parse = parse;
module.exports.validate = validate;
module.exports.normalize = normalize;
module.exports.find = find;

**Comment by metaraine** [comment] 2015-11-19 16:46
Maybe it's a bower error in finding bower.json. If you do `ncu -m bower --packageFile bower.json`, do you get the same error?

**Comment by MCKRUZ** [comment] 2015-11-19 16:49
Yeah I get the same error.  Do you think it's a bower issue maybe?  What version are you running

**Comment by metaraine** [comment] 2015-11-19 17:05
It seems to be a bower issue.

I don't even have bower installed and it works fine, because internally npm-check-updates uses bower `v1.5.3`.

**Comment by raineorshine** [comment] 2016-05-15 22:41
Closing in order to tidy up. I can re-open if it's still an issue or you have new information about what might be causing it.

**Closed by raineorshine** 2016-05-15 22:41 UTC
Labels: unable-to-reproduce
